user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # FastCGI Cache Configuration
    fastcgi_cache_path /var/cache/nginx levels=1:2 keys_zone=WORDPRESS:100m inactive=60m;
    fastcgi_cache_key "$scheme$request_method$host$request_uri";
    fastcgi_cache_use_stale error timeout invalid_header http_500;

    server {
        listen 80;
        server_name localhost; # Update to real domain later

        root /var/www/html;
        index index.php;

        # Handle WordPress pretty permalinks and fix 404 errors
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # Pass PHP scripts to PHP-FPM container on port 9000
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass simracing_wp:9000; # Call wordpress service inside docker network
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;

            # Enable FastCGI Cache for PHP requests
            fastcgi_cache WORDPRESS;
            fastcgi_cache_valid 200 301 302 1h; # Cache successful requests for 1 hour
        }

        # Cache static files directly and skip PHP execution
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg|eot)$ {
            expires max;
            log_not_found off;
        }
    }
}